[program:snapdraft-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/snapdraft/artisan queue:work redis --sleep=3 --tries=3 --timeout=600 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=3
redirect_stderr=true
stdout_logfile=/var/www/snapdraft/storage/logs/worker.log
stopwaitsecs=3600
