<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class GenerationHistory extends Model
{
    use HasFactory;

    /**
     * The table associated with the model.
     */
    protected $table = 'generation_history';

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'user_id',
        'project_id',
        'image_id',
        'ai_model',
        'prompt',
        'prompt_json',
        'compiled_prompt',
        'cluster_key',
        'json_valid',
        'tokens_used',
        'cost',
        'status',
        'error_message',
        'parameters',
        'request_data',
        'response_data',
    ];

    /**
     * The attributes that should be cast.
     */
    protected $casts = [
        'prompt_json' => 'array',
        'json_valid' => 'boolean',
        'tokens_used' => 'integer',
        'cost' => 'decimal:4',
        'parameters' => 'array',
        'request_data' => 'array',
        'response_data' => 'array',
    ];

    /**
     * Get the user that owns the generation history.
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Get the project associated with the generation.
     */
    public function project(): BelongsTo
    {
        return $this->belongsTo(Project::class);
    }

    /**
     * Get the image generated by this history record.
     */
    public function image(): BelongsTo
    {
        return $this->belongsTo(Image::class);
    }

    /**
     * Scope a query to only include pending generations.
     */
    public function scopePending($query)
    {
        return $query->where('status', 'pending');
    }

    /**
     * Scope a query to only include processing generations.
     */
    public function scopeProcessing($query)
    {
        return $query->where('status', 'processing');
    }

    /**
     * Scope a query to only include completed generations.
     */
    public function scopeCompleted($query)
    {
        return $query->where('status', 'completed');
    }

    /**
     * Scope a query to only include failed generations.
     */
    public function scopeFailed($query)
    {
        return $query->where('status', 'failed');
    }

    /**
     * Mark the generation as completed.
     */
    public function markAsCompleted(?array $responseData = null): void
    {
        $attributes = [
            'status' => 'completed',
            'response_data' => $responseData,
        ];

        if (isset($responseData['image_id'])) {
            $attributes['image_id'] = $responseData['image_id'];
        }

        $this->update($attributes);
    }

    /**
     * Mark the generation as failed.
     */
    public function markAsFailed(string $errorMessage): void
    {
        $this->update([
            'status' => 'failed',
            'error_message' => $errorMessage,
        ]);
    }
}